package com.skillbox.github.repository

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class RemoteRepositoryPublicJSON(
    val id: Long? = null,
    val node_id: String? = null,
    val name: String? = null,
    val full_name: String? = null,
    val private: Boolean = false,
    val owner: OwnerPublicRepoJSON? = null,
    val html_url: String? = null,
    val description: String? = null,
    val fork: Boolean = false,
    val url: String? = null,
    val forks_url: String? = null,
    val keys_url: String? = null,
    val collaborators_url: String? = null,
    val teams_url: String? = null,
    val hooks_url: String? = null,
    val issue_events_url: String? = null,
    val events_url: String? = null,
    val assignees_url: String? = null,
    val branches_url: String? = null,
    val tags_url: String? = null,
    val blobs_url: String? = null,
    val git_tags_url: String? = null,
    val git_refs_url: String? = null,
    val trees_url: String? = null,
    val statuses_url: String? = null,
    val languages_url: String? = null,
    val stargazers_url: String? = null,
    val contributors_url: String? = null,
    val subscribers_url: String? = null,
    val subscription_url: String? = null,
    val commits_url: String? = null,
    val git_commits_url: String? = null,
    val comments_url: String? = null,
    val issue_comment_url: String? = null,
    val contents_url: String? = null,
    val compare_url: String? = null,
    val merges_url: String? = null,
    val archive_url: String? = null,
    val downloads_url: String? = null,
    val issues_url: String? = null,
    val pulls_url: String? = null,
    val milestones_url: String? = null,
    val notifications_url: String? = null,
    val labels_url: String? = null,
    val releases_url: String? = null,
    val deployments_url: String? = null
)